name: cloud_pub_sub
version: 0.0.1
description: A sample command-line application.

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  googleapis: any
  googleapis_auth: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
